// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: spark_ssp_internal.proto

package spark_ssp

import (
	spark "github.com/lightsparkdev/spark/proto/spark"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryLostNodesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OwnerIdentityPubkey []byte                 `protobuf:"bytes,1,opt,name=owner_identity_pubkey,json=ownerIdentityPubkey,proto3" json:"owner_identity_pubkey,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryLostNodesRequest) Reset() {
	*x = QueryLostNodesRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLostNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLostNodesRequest) ProtoMessage() {}

func (x *QueryLostNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLostNodesRequest.ProtoReflect.Descriptor instead.
func (*QueryLostNodesRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{0}
}

func (x *QueryLostNodesRequest) GetOwnerIdentityPubkey() []byte {
	if x != nil {
		return x.OwnerIdentityPubkey
	}
	return nil
}

type QueryLostNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*spark.TreeNode      `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLostNodesResponse) Reset() {
	*x = QueryLostNodesResponse{}
	mi := &file_spark_ssp_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLostNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLostNodesResponse) ProtoMessage() {}

func (x *QueryLostNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLostNodesResponse.ProtoReflect.Descriptor instead.
func (*QueryLostNodesResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{1}
}

func (x *QueryLostNodesResponse) GetNodes() []*spark.TreeNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_spark_ssp_internal_proto protoreflect.FileDescriptor

const file_spark_ssp_internal_proto_rawDesc = "" +
	"\n" +
	"\x18spark_ssp_internal.proto\x12\tspark_ssp\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vspark.proto\"K\n" +
	"\x15QueryLostNodesRequest\x122\n" +
	"\x15owner_identity_pubkey\x18\x01 \x01(\fR\x13ownerIdentityPubkey\"?\n" +
	"\x16QueryLostNodesResponse\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.spark.TreeNodeR\x05nodes2t\n" +
	"\x17SparkSspInternalService\x12Y\n" +
	"\x10query_lost_nodes\x12 .spark_ssp.QueryLostNodesRequest\x1a!.spark_ssp.QueryLostNodesResponse\"\x00B0Z.github.com/lightsparkdev/spark/proto/spark_sspb\x06proto3"

var (
	file_spark_ssp_internal_proto_rawDescOnce sync.Once
	file_spark_ssp_internal_proto_rawDescData []byte
)

func file_spark_ssp_internal_proto_rawDescGZIP() []byte {
	file_spark_ssp_internal_proto_rawDescOnce.Do(func() {
		file_spark_ssp_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_ssp_internal_proto_rawDesc), len(file_spark_ssp_internal_proto_rawDesc)))
	})
	return file_spark_ssp_internal_proto_rawDescData
}

var file_spark_ssp_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spark_ssp_internal_proto_goTypes = []any{
	(*QueryLostNodesRequest)(nil),  // 0: spark_ssp.QueryLostNodesRequest
	(*QueryLostNodesResponse)(nil), // 1: spark_ssp.QueryLostNodesResponse
	(*spark.TreeNode)(nil),         // 2: spark.TreeNode
}
var file_spark_ssp_internal_proto_depIdxs = []int32{
	2, // 0: spark_ssp.QueryLostNodesResponse.nodes:type_name -> spark.TreeNode
	0, // 1: spark_ssp.SparkSspInternalService.query_lost_nodes:input_type -> spark_ssp.QueryLostNodesRequest
	1, // 2: spark_ssp.SparkSspInternalService.query_lost_nodes:output_type -> spark_ssp.QueryLostNodesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spark_ssp_internal_proto_init() }
func file_spark_ssp_internal_proto_init() {
	if File_spark_ssp_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_ssp_internal_proto_rawDesc), len(file_spark_ssp_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spark_ssp_internal_proto_goTypes,
		DependencyIndexes: file_spark_ssp_internal_proto_depIdxs,
		MessageInfos:      file_spark_ssp_internal_proto_msgTypes,
	}.Build()
	File_spark_ssp_internal_proto = out.File
	file_spark_ssp_internal_proto_goTypes = nil
	file_spark_ssp_internal_proto_depIdxs = nil
}
