// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: spark_ssp_internal.proto

package spark_ssp

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on QueryLostNodesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryLostNodesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryLostNodesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryLostNodesRequestMultiError, or nil if none found.
func (m *QueryLostNodesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryLostNodesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OwnerIdentityPubkey

	if len(errors) > 0 {
		return QueryLostNodesRequestMultiError(errors)
	}

	return nil
}

// QueryLostNodesRequestMultiError is an error wrapping multiple validation
// errors returned by QueryLostNodesRequest.ValidateAll() if the designated
// constraints aren't met.
type QueryLostNodesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryLostNodesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryLostNodesRequestMultiError) AllErrors() []error { return m }

// QueryLostNodesRequestValidationError is the validation error returned by
// QueryLostNodesRequest.Validate if the designated constraints aren't met.
type QueryLostNodesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryLostNodesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryLostNodesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryLostNodesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryLostNodesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryLostNodesRequestValidationError) ErrorName() string {
	return "QueryLostNodesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e QueryLostNodesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryLostNodesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryLostNodesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryLostNodesRequestValidationError{}

// Validate checks the field values on QueryLostNodesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *QueryLostNodesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueryLostNodesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// QueryLostNodesResponseMultiError, or nil if none found.
func (m *QueryLostNodesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *QueryLostNodesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetNodes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueryLostNodesResponseValidationError{
						field:  fmt.Sprintf("Nodes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueryLostNodesResponseValidationError{
						field:  fmt.Sprintf("Nodes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueryLostNodesResponseValidationError{
					field:  fmt.Sprintf("Nodes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return QueryLostNodesResponseMultiError(errors)
	}

	return nil
}

// QueryLostNodesResponseMultiError is an error wrapping multiple validation
// errors returned by QueryLostNodesResponse.ValidateAll() if the designated
// constraints aren't met.
type QueryLostNodesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueryLostNodesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueryLostNodesResponseMultiError) AllErrors() []error { return m }

// QueryLostNodesResponseValidationError is the validation error returned by
// QueryLostNodesResponse.Validate if the designated constraints aren't met.
type QueryLostNodesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueryLostNodesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueryLostNodesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueryLostNodesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueryLostNodesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueryLostNodesResponseValidationError) ErrorName() string {
	return "QueryLostNodesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e QueryLostNodesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueryLostNodesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueryLostNodesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueryLostNodesResponseValidationError{}
